create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.instruments (
  id bigint generated by default as identity primary key,
  name text
);

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  email text,
  display_name varchar,
  stripe_customer_id text unique,
  role text
);

create table public.posters (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text,
  collection text,
  image_url text,
  status text not null default 'draft',
  sort_order integer,
  created_at timestamptz default now(),
  updated_at timestamptz
);

create table public.variants (
  id bigint generated by default as identity primary key,
  poster_id bigint not null references public.posters(id) on delete cascade,
  sku text,
  width_in smallint,
  height_in smallint,
  paper_type text,
  price_cents integer not null,
  currency text not null default 'usd',
  stripe_price_id text unique,
  is_active boolean not null default true,
  production_notes text,
  created_at timestamptz default now(),
  updated_at timestamptz,
  label text
);

create table public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.customer_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  stripe_customer_id text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  user_id uuid references auth.users(id) on delete set null,
  stripe_customer_id text,
  stripe_checkout_session_id text unique,
  stripe_payment_intent_id text,
  payment_status text,
  fulfillment_status text,
  subtotal_cents integer,
  shipping_cents integer,
  tax_cents integer,
  total_cents integer,
  currency text,
  customer_email text,
  shipping_name text,
  shipping_address_line1 text,
  shipping_address_line2 text,
  shipping_city text,
  shipping_state text,
  shipping_postal_code text,
  shipping_country text,
  tracking_number text,
  paid_at timestamptz,
  shipped_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  variant_id bigint references public.variants(id) on delete set null,
  poster_id bigint references public.posters(id) on delete set null,
  quantity integer,
  unit_price_cents integer,
  line_total_cents integer,
  poster_title_snapshot text,
  variant_label_snapshot text,
  poster_image_snapshot text,
  created_at timestamptz default now()
);

create index posters_active_created_at_idx
  on public.posters(created_at desc)
  where status = 'active';

create index posters_slug_status_idx
  on public.posters(slug, status);

create index variants_poster_active_price_idx
  on public.variants(poster_id, is_active, price_cents);

create index orders_user_created_at_idx
  on public.orders(user_id, created_at desc);

create index orders_stripe_customer_id_idx
  on public.orders(stripe_customer_id)
  where stripe_customer_id is not null;

create index orders_created_at_idx
  on public.orders(created_at desc);

create index orders_payment_status_idx
  on public.orders(payment_status);

create index orders_fulfillment_status_idx
  on public.orders(fulfillment_status);

create index order_items_order_id_idx
  on public.order_items(order_id);

create index order_items_poster_id_idx
  on public.order_items(poster_id);

create index order_items_variant_id_idx
  on public.order_items(variant_id);

create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

create trigger set_posters_updated_at
before update on public.posters
for each row
execute function public.set_updated_at();

create trigger set_variants_updated_at
before update on public.variants
for each row
execute function public.set_updated_at();

create trigger set_customer_profiles_updated_at
before update on public.customer_profiles
for each row
execute function public.set_updated_at();

create trigger set_orders_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();

create or replace function public.is_store_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  );
$$;

alter table public.instruments enable row level security;
alter table public.profiles enable row level security;
alter table public.posters enable row level security;
alter table public.variants enable row level security;
alter table public.admin_users enable row level security;
alter table public.customer_profiles enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "Users can read their own profile"
on public.profiles
for select
to authenticated
using (user_id = auth.uid());

create policy "Users can update their own profile"
on public.profiles
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy "Active posters are publicly readable"
on public.posters
for select
using (status = 'active');

create policy "Admins can manage posters"
on public.posters
for all
to authenticated
using (public.is_store_admin())
with check (public.is_store_admin());

create policy "Active variants for active posters are publicly readable"
on public.variants
for select
using (
  is_active
  and exists (
    select 1
    from public.posters
    where posters.id = variants.poster_id
      and posters.status = 'active'
  )
);

create policy "Admins can manage variants"
on public.variants
for all
to authenticated
using (public.is_store_admin())
with check (public.is_store_admin());

create policy "Admins can read admin users"
on public.admin_users
for select
to authenticated
using (public.is_store_admin());

create policy "Users can read their own admin user row"
on public.admin_users
for select
to authenticated
using (user_id = auth.uid());

create policy "Admins can manage admin users"
on public.admin_users
for all
to authenticated
using (public.is_store_admin())
with check (public.is_store_admin());

create policy "Users can read their own customer profile"
on public.customer_profiles
for select
to authenticated
using (user_id = auth.uid());

create policy "Admins can read all customer profiles"
on public.customer_profiles
for select
to authenticated
using (public.is_store_admin());

create policy "Users can read their own orders"
on public.orders
for select
to authenticated
using (user_id = auth.uid());

create policy "Admins can read all orders"
on public.orders
for select
to authenticated
using (public.is_store_admin());

create policy "Admins can update orders"
on public.orders
for update
to authenticated
using (public.is_store_admin())
with check (public.is_store_admin());

create policy "Users can read their own order items"
on public.order_items
for select
to authenticated
using (
  exists (
    select 1
    from public.orders
    where orders.id = order_items.order_id
      and orders.user_id = auth.uid()
  )
);

create policy "Admins can read all order items"
on public.order_items
for select
to authenticated
using (public.is_store_admin());

create policy "Admins can update order items"
on public.order_items
for update
to authenticated
using (public.is_store_admin())
with check (public.is_store_admin());

grant usage on schema public to anon, authenticated;

grant select on public.posters to anon, authenticated;
grant select on public.variants to anon, authenticated;
grant insert, update, delete on public.posters to authenticated;
grant insert, update, delete on public.variants to authenticated;

grant select, update on public.profiles to authenticated;

grant select on public.admin_users to authenticated;
grant insert, update, delete on public.admin_users to authenticated;

grant select on public.customer_profiles to authenticated;

grant select on public.orders to authenticated;
grant update (
  payment_status,
  fulfillment_status,
  stripe_payment_intent_id,
  subtotal_cents,
  shipping_cents,
  tax_cents,
  total_cents,
  currency,
  customer_email,
  shipping_name,
  shipping_address_line1,
  shipping_address_line2,
  shipping_city,
  shipping_state,
  shipping_postal_code,
  shipping_country,
  tracking_number,
  paid_at,
  shipped_at,
  updated_at
) on public.orders to authenticated;

grant select on public.order_items to authenticated;
grant update (
  quantity,
  unit_price_cents,
  line_total_cents,
  poster_title_snapshot,
  variant_label_snapshot,
  poster_image_snapshot
) on public.order_items to authenticated;

grant all on public.instruments to service_role;
grant all on public.profiles to service_role;
grant all on public.posters to service_role;
grant all on public.variants to service_role;
grant all on public.admin_users to service_role;
grant all on public.customer_profiles to service_role;
grant all on public.orders to service_role;
grant all on public.order_items to service_role;

grant usage, select on all sequences in schema public to service_role;
