create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.posters (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  description text,
  image_url text not null,
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint posters_status_check
    check (status in ('draft', 'active', 'archived')),
  constraint posters_slug_check
    check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create table public.variants (
  id bigint generated by default as identity primary key,
  poster_id bigint not null references public.posters(id) on delete cascade,
  sku text not null unique,
  label text not null,
  width_in numeric(6, 2) not null,
  height_in numeric(6, 2) not null,
  paper_type text not null,
  price_cents integer not null,
  currency text not null default 'usd',
  stripe_price_id text,
  is_active boolean not null default true,
  production_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint variants_size_check
    check (width_in > 0 and height_in > 0),
  constraint variants_price_check
    check (price_cents >= 0),
  constraint variants_currency_check
    check (currency = lower(currency) and currency ~ '^[a-z]{3}$')
);

create table public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  stripe_customer_id text,
  stripe_checkout_session_id text unique,
  stripe_payment_intent_id text,
  payment_status text not null default 'pending',
  fulfillment_status text not null default 'unfulfilled',
  subtotal_cents integer not null default 0,
  shipping_cents integer not null default 0,
  tax_cents integer not null default 0,
  total_cents integer not null default 0,
  currency text not null default 'usd',
  shipping_name text,
  shipping_address jsonb,
  tracking_number text,
  tracking_url text,
  paid_at timestamptz,
  canceled_at timestamptz,
  refunded_at timestamptz,
  shipped_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint orders_payment_status_check
    check (payment_status in ('pending', 'paid', 'failed', 'refunded', 'canceled')),
  constraint orders_fulfillment_status_check
    check (fulfillment_status in ('unfulfilled', 'processing', 'shipped', 'delivered', 'canceled')),
  constraint orders_totals_check
    check (
      subtotal_cents >= 0
      and shipping_cents >= 0
      and tax_cents >= 0
      and total_cents >= 0
    ),
  constraint orders_currency_check
    check (currency = lower(currency) and currency ~ '^[a-z]{3}$')
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  poster_id bigint not null references public.posters(id) on delete restrict,
  variant_id bigint not null references public.variants(id) on delete restrict,
  quantity integer not null,
  unit_price_cents integer not null,
  currency text not null default 'usd',
  poster_title text not null,
  variant_label text not null,
  variant_sku text not null,
  created_at timestamptz not null default now(),

  constraint order_items_quantity_check
    check (quantity > 0),
  constraint order_items_unit_price_check
    check (unit_price_cents >= 0),
  constraint order_items_currency_check
    check (currency = lower(currency) and currency ~ '^[a-z]{3}$')
);

create unique index variants_stripe_price_id_key
  on public.variants(stripe_price_id)
  where stripe_price_id is not null;

create index posters_active_created_at_idx
  on public.posters(created_at desc)
  where status = 'active';

create index posters_slug_status_idx
  on public.posters(slug, status);

create index variants_poster_active_price_idx
  on public.variants(poster_id, is_active, price_cents);

create index orders_user_created_at_idx
  on public.orders(user_id, created_at desc);

create index orders_created_at_idx
  on public.orders(created_at desc);

create index orders_payment_status_idx
  on public.orders(payment_status);

create index orders_fulfillment_status_idx
  on public.orders(fulfillment_status);

create index order_items_order_id_idx
  on public.order_items(order_id);

create index order_items_poster_id_idx
  on public.order_items(poster_id);

create index order_items_variant_id_idx
  on public.order_items(variant_id);

create trigger set_posters_updated_at
before update on public.posters
for each row
execute function public.set_updated_at();

create trigger set_variants_updated_at
before update on public.variants
for each row
execute function public.set_updated_at();

create trigger set_orders_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();

create or replace function public.is_store_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  );
$$;

alter table public.posters enable row level security;
alter table public.variants enable row level security;
alter table public.admin_users enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "Active posters are publicly readable"
on public.posters
for select
using (status = 'active');

create policy "Admins can manage posters"
on public.posters
for all
to authenticated
using (public.is_store_admin())
with check (public.is_store_admin());

create policy "Active variants for active posters are publicly readable"
on public.variants
for select
using (
  is_active
  and exists (
    select 1
    from public.posters
    where posters.id = variants.poster_id
      and posters.status = 'active'
  )
);

create policy "Admins can manage variants"
on public.variants
for all
to authenticated
using (public.is_store_admin())
with check (public.is_store_admin());

create policy "Admins can read admin users"
on public.admin_users
for select
to authenticated
using (public.is_store_admin());

create policy "Users can read their own admin user row"
on public.admin_users
for select
to authenticated
using (user_id = auth.uid());

create policy "Admins can manage admin users"
on public.admin_users
for all
to authenticated
using (public.is_store_admin())
with check (public.is_store_admin());

create policy "Users can read their own orders"
on public.orders
for select
to authenticated
using (user_id = auth.uid());

create policy "Admins can read all orders"
on public.orders
for select
to authenticated
using (public.is_store_admin());

create policy "Admins can update orders"
on public.orders
for update
to authenticated
using (public.is_store_admin())
with check (public.is_store_admin());

create policy "Users can read their own order items"
on public.order_items
for select
to authenticated
using (
  exists (
    select 1
    from public.orders
    where orders.id = order_items.order_id
      and orders.user_id = auth.uid()
  )
);

create policy "Admins can read all order items"
on public.order_items
for select
to authenticated
using (public.is_store_admin());

create policy "Admins can update order items"
on public.order_items
for update
to authenticated
using (public.is_store_admin())
with check (public.is_store_admin());

grant usage on schema public to anon, authenticated;

grant select on public.posters to anon, authenticated;
grant select on public.variants to anon, authenticated;
grant insert, update, delete on public.posters to authenticated;
grant insert, update, delete on public.variants to authenticated;

grant select on public.admin_users to authenticated;
grant insert, update, delete on public.admin_users to authenticated;

grant select on public.orders to authenticated;
grant update (
  payment_status,
  fulfillment_status,
  shipping_name,
  shipping_address,
  tracking_number,
  tracking_url,
  paid_at,
  canceled_at,
  refunded_at,
  shipped_at,
  delivered_at,
  updated_at
) on public.orders to authenticated;

grant select on public.order_items to authenticated;
grant update (
  quantity,
  unit_price_cents,
  currency,
  poster_title,
  variant_label,
  variant_sku
) on public.order_items to authenticated;

grant all on public.posters to service_role;
grant all on public.variants to service_role;
grant all on public.admin_users to service_role;
grant all on public.orders to service_role;
grant all on public.order_items to service_role;

grant usage, select on all sequences in schema public to service_role;
